//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "rooms")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub room_id: String,
    pub owner_pid: Uuid,
    pub name: String,
    pub max_players: i16,
    pub status: String,
    pub payment_type: Option<String>,
    pub rounds: Option<i16>,
    pub banker_type: Option<String>,
    pub max_banker_multi: Option<i16>,
    pub idle_push_multi: Option<i16>,
    pub base_score_numerator: Option<i16>,
    pub base_score_denominator: Option<i16>,
    pub multiply_rule: Option<String>,
    pub special_cards: Option<Json>,
    pub joker_rule: Option<String>,
    pub flower_rule: Option<String>,
    #[sea_orm(unique)]
    pub room_password: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
